// flow-typed signature: af80e12d8118e55aa3d7b776e3cce4fe
// flow-typed version: <<STUB>>/babel-plugin-preval_v3.0.1/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-preval'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-preval' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-preval/dist/helpers' {
  declare module.exports: any;
}

declare module 'babel-plugin-preval/dist/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-preval/dist/macro' {
  declare module.exports: any;
}

declare module 'babel-plugin-preval/dist/object-to-ast' {
  declare module.exports: any;
}

declare module 'babel-plugin-preval/macro' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-preval/dist/helpers.js' {
  declare module.exports: $Exports<'babel-plugin-preval/dist/helpers'>;
}
declare module 'babel-plugin-preval/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-preval/dist/index'>;
}
declare module 'babel-plugin-preval/dist/macro.js' {
  declare module.exports: $Exports<'babel-plugin-preval/dist/macro'>;
}
declare module 'babel-plugin-preval/dist/object-to-ast.js' {
  declare module.exports: $Exports<'babel-plugin-preval/dist/object-to-ast'>;
}
declare module 'babel-plugin-preval/macro.js' {
  declare module.exports: $Exports<'babel-plugin-preval/macro'>;
}
