// flow-typed signature: f2d1e5220e7601112e53c7580ff8403e
// flow-typed version: <<STUB>>/babel-plugin-syntax-trailing-function-commas_v^6.22.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-syntax-trailing-function-commas'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-syntax-trailing-function-commas' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-syntax-trailing-function-commas/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-syntax-trailing-function-commas/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-syntax-trailing-function-commas/lib/index'>;
}
