// flow-typed signature: 175d94bd26694c5b407cdbd9884feda5
// flow-typed version: <<STUB>>/babel-plugin-annotate-pure-calls_v^0.3.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-annotate-pure-calls'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-annotate-pure-calls' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-annotate-pure-calls/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-annotate-pure-calls/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-annotate-pure-calls/lib/index'>;
}
