// flow-typed signature: 82700468a903ac7f54f8e62507773a66
// flow-typed version: <<STUB>>/concat-stream_v^1.5.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'concat-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'concat-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'concat-stream/index' {
  declare module.exports: $Exports<'concat-stream'>;
}
declare module 'concat-stream/index.js' {
  declare module.exports: $Exports<'concat-stream'>;
}
