// flow-typed signature: ebc1cae4991726da1806299be6075570
// flow-typed version: <<STUB>>/cz-conventional-changelog_v^1.2.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cz-conventional-changelog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cz-conventional-changelog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cz-conventional-changelog/engine' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cz-conventional-changelog/engine.js' {
  declare module.exports: $Exports<'cz-conventional-changelog/engine'>;
}
declare module 'cz-conventional-changelog/index' {
  declare module.exports: $Exports<'cz-conventional-changelog'>;
}
declare module 'cz-conventional-changelog/index.js' {
  declare module.exports: $Exports<'cz-conventional-changelog'>;
}
