// flow-typed signature: 34f78f7bb7f0a345456df1dd5ff973b4
// flow-typed version: <<STUB>>/documentation_v^4.0.0-beta.18/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'documentation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'documentation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'documentation/bin/documentation' {
  declare module.exports: any;
}

declare module 'documentation/default_theme/assets/anchor' {
  declare module.exports: any;
}

declare module 'documentation/default_theme/assets/site' {
  declare module.exports: any;
}

declare module 'documentation/default_theme/index' {
  declare module.exports: any;
}

declare module 'documentation/lib/commands/build' {
  declare module.exports: any;
}

declare module 'documentation/lib/commands/index' {
  declare module.exports: any;
}

declare module 'documentation/lib/commands/lint' {
  declare module.exports: any;
}

declare module 'documentation/lib/commands/readme' {
  declare module.exports: any;
}

declare module 'documentation/lib/commands/serve' {
  declare module.exports: any;
}

declare module 'documentation/lib/commands/shared_options' {
  declare module.exports: any;
}

declare module 'documentation/lib/extractors/comments' {
  declare module.exports: any;
}

declare module 'documentation/lib/extractors/exported' {
  declare module.exports: any;
}

declare module 'documentation/lib/filter_access' {
  declare module.exports: any;
}

declare module 'documentation/lib/flow_doctrine' {
  declare module.exports: any;
}

declare module 'documentation/lib/garbage_collect' {
  declare module.exports: any;
}

declare module 'documentation/lib/git/find_git' {
  declare module.exports: any;
}

declare module 'documentation/lib/git/url_prefix' {
  declare module.exports: any;
}

declare module 'documentation/lib/github' {
  declare module.exports: any;
}

declare module 'documentation/lib/hierarchy' {
  declare module.exports: any;
}

declare module 'documentation/lib/infer/access' {
  declare module.exports: any;
}

declare module 'documentation/lib/infer/augments' {
  declare module.exports: any;
}

declare module 'documentation/lib/infer/finders' {
  declare module.exports: any;
}

declare module 'documentation/lib/infer/kind' {
  declare module.exports: any;
}

declare module 'documentation/lib/infer/membership' {
  declare module.exports: any;
}

declare module 'documentation/lib/infer/name' {
  declare module.exports: any;
}

declare module 'documentation/lib/infer/params' {
  declare module.exports: any;
}

declare module 'documentation/lib/infer/properties' {
  declare module.exports: any;
}

declare module 'documentation/lib/infer/return' {
  declare module.exports: any;
}

declare module 'documentation/lib/infer/should_skip_inference' {
  declare module.exports: any;
}

declare module 'documentation/lib/infer/type' {
  declare module.exports: any;
}

declare module 'documentation/lib/inline_tokenizer' {
  declare module.exports: any;
}

declare module 'documentation/lib/input/dependency' {
  declare module.exports: any;
}

declare module 'documentation/lib/input/shallow' {
  declare module.exports: any;
}

declare module 'documentation/lib/is_jsdoc_comment' {
  declare module.exports: any;
}

declare module 'documentation/lib/lint' {
  declare module.exports: any;
}

declare module 'documentation/lib/load_config' {
  declare module.exports: any;
}

declare module 'documentation/lib/module_filters' {
  declare module.exports: any;
}

declare module 'documentation/lib/nest' {
  declare module.exports: any;
}

declare module 'documentation/lib/output/highlighter' {
  declare module.exports: any;
}

declare module 'documentation/lib/output/html' {
  declare module.exports: any;
}

declare module 'documentation/lib/output/json' {
  declare module.exports: any;
}

declare module 'documentation/lib/output/markdown_ast' {
  declare module.exports: any;
}

declare module 'documentation/lib/output/markdown' {
  declare module.exports: any;
}

declare module 'documentation/lib/output/util/format_type' {
  declare module.exports: any;
}

declare module 'documentation/lib/output/util/formatters' {
  declare module.exports: any;
}

declare module 'documentation/lib/output/util/linker_stack' {
  declare module.exports: any;
}

declare module 'documentation/lib/output/util/reroute_links' {
  declare module.exports: any;
}

declare module 'documentation/lib/parse_markdown' {
  declare module.exports: any;
}

declare module 'documentation/lib/parse' {
  declare module.exports: any;
}

declare module 'documentation/lib/parsers/javascript' {
  declare module.exports: any;
}

declare module 'documentation/lib/parsers/parse_to_ast' {
  declare module.exports: any;
}

declare module 'documentation/lib/parsers/polyglot' {
  declare module.exports: any;
}

declare module 'documentation/lib/serve/error_page' {
  declare module.exports: any;
}

declare module 'documentation/lib/serve/server' {
  declare module.exports: any;
}

declare module 'documentation/lib/smart_glob' {
  declare module.exports: any;
}

declare module 'documentation/lib/sort' {
  declare module.exports: any;
}

declare module 'documentation/lib/walk' {
  declare module.exports: any;
}

// Filename aliases
declare module 'documentation/bin/documentation.js' {
  declare module.exports: $Exports<'documentation/bin/documentation'>;
}
declare module 'documentation/default_theme/assets/anchor.js' {
  declare module.exports: $Exports<'documentation/default_theme/assets/anchor'>;
}
declare module 'documentation/default_theme/assets/site.js' {
  declare module.exports: $Exports<'documentation/default_theme/assets/site'>;
}
declare module 'documentation/default_theme/index.js' {
  declare module.exports: $Exports<'documentation/default_theme/index'>;
}
declare module 'documentation/index' {
  declare module.exports: $Exports<'documentation'>;
}
declare module 'documentation/index.js' {
  declare module.exports: $Exports<'documentation'>;
}
declare module 'documentation/lib/commands/build.js' {
  declare module.exports: $Exports<'documentation/lib/commands/build'>;
}
declare module 'documentation/lib/commands/index.js' {
  declare module.exports: $Exports<'documentation/lib/commands/index'>;
}
declare module 'documentation/lib/commands/lint.js' {
  declare module.exports: $Exports<'documentation/lib/commands/lint'>;
}
declare module 'documentation/lib/commands/readme.js' {
  declare module.exports: $Exports<'documentation/lib/commands/readme'>;
}
declare module 'documentation/lib/commands/serve.js' {
  declare module.exports: $Exports<'documentation/lib/commands/serve'>;
}
declare module 'documentation/lib/commands/shared_options.js' {
  declare module.exports: $Exports<'documentation/lib/commands/shared_options'>;
}
declare module 'documentation/lib/extractors/comments.js' {
  declare module.exports: $Exports<'documentation/lib/extractors/comments'>;
}
declare module 'documentation/lib/extractors/exported.js' {
  declare module.exports: $Exports<'documentation/lib/extractors/exported'>;
}
declare module 'documentation/lib/filter_access.js' {
  declare module.exports: $Exports<'documentation/lib/filter_access'>;
}
declare module 'documentation/lib/flow_doctrine.js' {
  declare module.exports: $Exports<'documentation/lib/flow_doctrine'>;
}
declare module 'documentation/lib/garbage_collect.js' {
  declare module.exports: $Exports<'documentation/lib/garbage_collect'>;
}
declare module 'documentation/lib/git/find_git.js' {
  declare module.exports: $Exports<'documentation/lib/git/find_git'>;
}
declare module 'documentation/lib/git/url_prefix.js' {
  declare module.exports: $Exports<'documentation/lib/git/url_prefix'>;
}
declare module 'documentation/lib/github.js' {
  declare module.exports: $Exports<'documentation/lib/github'>;
}
declare module 'documentation/lib/hierarchy.js' {
  declare module.exports: $Exports<'documentation/lib/hierarchy'>;
}
declare module 'documentation/lib/infer/access.js' {
  declare module.exports: $Exports<'documentation/lib/infer/access'>;
}
declare module 'documentation/lib/infer/augments.js' {
  declare module.exports: $Exports<'documentation/lib/infer/augments'>;
}
declare module 'documentation/lib/infer/finders.js' {
  declare module.exports: $Exports<'documentation/lib/infer/finders'>;
}
declare module 'documentation/lib/infer/kind.js' {
  declare module.exports: $Exports<'documentation/lib/infer/kind'>;
}
declare module 'documentation/lib/infer/membership.js' {
  declare module.exports: $Exports<'documentation/lib/infer/membership'>;
}
declare module 'documentation/lib/infer/name.js' {
  declare module.exports: $Exports<'documentation/lib/infer/name'>;
}
declare module 'documentation/lib/infer/params.js' {
  declare module.exports: $Exports<'documentation/lib/infer/params'>;
}
declare module 'documentation/lib/infer/properties.js' {
  declare module.exports: $Exports<'documentation/lib/infer/properties'>;
}
declare module 'documentation/lib/infer/return.js' {
  declare module.exports: $Exports<'documentation/lib/infer/return'>;
}
declare module 'documentation/lib/infer/should_skip_inference.js' {
  declare module.exports: $Exports<'documentation/lib/infer/should_skip_inference'>;
}
declare module 'documentation/lib/infer/type.js' {
  declare module.exports: $Exports<'documentation/lib/infer/type'>;
}
declare module 'documentation/lib/inline_tokenizer.js' {
  declare module.exports: $Exports<'documentation/lib/inline_tokenizer'>;
}
declare module 'documentation/lib/input/dependency.js' {
  declare module.exports: $Exports<'documentation/lib/input/dependency'>;
}
declare module 'documentation/lib/input/shallow.js' {
  declare module.exports: $Exports<'documentation/lib/input/shallow'>;
}
declare module 'documentation/lib/is_jsdoc_comment.js' {
  declare module.exports: $Exports<'documentation/lib/is_jsdoc_comment'>;
}
declare module 'documentation/lib/lint.js' {
  declare module.exports: $Exports<'documentation/lib/lint'>;
}
declare module 'documentation/lib/load_config.js' {
  declare module.exports: $Exports<'documentation/lib/load_config'>;
}
declare module 'documentation/lib/module_filters.js' {
  declare module.exports: $Exports<'documentation/lib/module_filters'>;
}
declare module 'documentation/lib/nest.js' {
  declare module.exports: $Exports<'documentation/lib/nest'>;
}
declare module 'documentation/lib/output/highlighter.js' {
  declare module.exports: $Exports<'documentation/lib/output/highlighter'>;
}
declare module 'documentation/lib/output/html.js' {
  declare module.exports: $Exports<'documentation/lib/output/html'>;
}
declare module 'documentation/lib/output/json.js' {
  declare module.exports: $Exports<'documentation/lib/output/json'>;
}
declare module 'documentation/lib/output/markdown_ast.js' {
  declare module.exports: $Exports<'documentation/lib/output/markdown_ast'>;
}
declare module 'documentation/lib/output/markdown.js' {
  declare module.exports: $Exports<'documentation/lib/output/markdown'>;
}
declare module 'documentation/lib/output/util/format_type.js' {
  declare module.exports: $Exports<'documentation/lib/output/util/format_type'>;
}
declare module 'documentation/lib/output/util/formatters.js' {
  declare module.exports: $Exports<'documentation/lib/output/util/formatters'>;
}
declare module 'documentation/lib/output/util/linker_stack.js' {
  declare module.exports: $Exports<'documentation/lib/output/util/linker_stack'>;
}
declare module 'documentation/lib/output/util/reroute_links.js' {
  declare module.exports: $Exports<'documentation/lib/output/util/reroute_links'>;
}
declare module 'documentation/lib/parse_markdown.js' {
  declare module.exports: $Exports<'documentation/lib/parse_markdown'>;
}
declare module 'documentation/lib/parse.js' {
  declare module.exports: $Exports<'documentation/lib/parse'>;
}
declare module 'documentation/lib/parsers/javascript.js' {
  declare module.exports: $Exports<'documentation/lib/parsers/javascript'>;
}
declare module 'documentation/lib/parsers/parse_to_ast.js' {
  declare module.exports: $Exports<'documentation/lib/parsers/parse_to_ast'>;
}
declare module 'documentation/lib/parsers/polyglot.js' {
  declare module.exports: $Exports<'documentation/lib/parsers/polyglot'>;
}
declare module 'documentation/lib/serve/error_page.js' {
  declare module.exports: $Exports<'documentation/lib/serve/error_page'>;
}
declare module 'documentation/lib/serve/server.js' {
  declare module.exports: $Exports<'documentation/lib/serve/server'>;
}
declare module 'documentation/lib/smart_glob.js' {
  declare module.exports: $Exports<'documentation/lib/smart_glob'>;
}
declare module 'documentation/lib/sort.js' {
  declare module.exports: $Exports<'documentation/lib/sort'>;
}
declare module 'documentation/lib/walk.js' {
  declare module.exports: $Exports<'documentation/lib/walk'>;
}
