// flow-typed signature: a2035709754ffb2c835f8c7919aa007d
// flow-typed version: <<STUB>>/documentation_v12.3.0/flow_v0.227.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'documentation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'documentation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'documentation/babel.config' {
  declare module.exports: any;
}

declare module 'documentation/bin/documentation' {
  declare module.exports: any;
}

declare module 'documentation/declarations/comment' {
  declare module.exports: any;
}

declare module 'documentation/src/commands/build' {
  declare module.exports: any;
}

declare module 'documentation/src/commands' {
  declare module.exports: any;
}

declare module 'documentation/src/commands/lint' {
  declare module.exports: any;
}

declare module 'documentation/src/commands/readme' {
  declare module.exports: any;
}

declare module 'documentation/src/commands/serve' {
  declare module.exports: any;
}

declare module 'documentation/src/commands/shared_options' {
  declare module.exports: any;
}

declare module 'documentation/src/default_theme/assets/anchor' {
  declare module.exports: any;
}

declare module 'documentation/src/default_theme/assets/site' {
  declare module.exports: any;
}

declare module 'documentation/src/default_theme/assets/split' {
  declare module.exports: any;
}

declare module 'documentation/src/default_theme' {
  declare module.exports: any;
}

declare module 'documentation/src/extractors/comments' {
  declare module.exports: any;
}

declare module 'documentation/src/extractors/exported' {
  declare module.exports: any;
}

declare module 'documentation/src/filter_access' {
  declare module.exports: any;
}

declare module 'documentation/src/flow_doctrine' {
  declare module.exports: any;
}

declare module 'documentation/src/garbage_collect' {
  declare module.exports: any;
}

declare module 'documentation/src/get-readme-file' {
  declare module.exports: any;
}

declare module 'documentation/src/git/find_git' {
  declare module.exports: any;
}

declare module 'documentation/src/git/url_prefix' {
  declare module.exports: any;
}

declare module 'documentation/src/github' {
  declare module.exports: any;
}

declare module 'documentation/src/hierarchy' {
  declare module.exports: any;
}

declare module 'documentation/src' {
  declare module.exports: any;
}

declare module 'documentation/src/infer/access' {
  declare module.exports: any;
}

declare module 'documentation/src/infer/augments' {
  declare module.exports: any;
}

declare module 'documentation/src/infer/finders' {
  declare module.exports: any;
}

declare module 'documentation/src/infer/implements' {
  declare module.exports: any;
}

declare module 'documentation/src/infer/kind' {
  declare module.exports: any;
}

declare module 'documentation/src/infer/membership' {
  declare module.exports: any;
}

declare module 'documentation/src/infer/name' {
  declare module.exports: any;
}

declare module 'documentation/src/infer/params' {
  declare module.exports: any;
}

declare module 'documentation/src/infer/properties' {
  declare module.exports: any;
}

declare module 'documentation/src/infer/return' {
  declare module.exports: any;
}

declare module 'documentation/src/infer/type' {
  declare module.exports: any;
}

declare module 'documentation/src/inline_tokenizer' {
  declare module.exports: any;
}

declare module 'documentation/src/input/dependency' {
  declare module.exports: any;
}

declare module 'documentation/src/input/shallow' {
  declare module.exports: any;
}

declare module 'documentation/src/is_jsdoc_comment' {
  declare module.exports: any;
}

declare module 'documentation/src/lint' {
  declare module.exports: any;
}

declare module 'documentation/src/merge_config' {
  declare module.exports: any;
}

declare module 'documentation/src/module_filters' {
  declare module.exports: any;
}

declare module 'documentation/src/nest' {
  declare module.exports: any;
}

declare module 'documentation/src/output/highlighter' {
  declare module.exports: any;
}

declare module 'documentation/src/output/html' {
  declare module.exports: any;
}

declare module 'documentation/src/output/json' {
  declare module.exports: any;
}

declare module 'documentation/src/output/markdown_ast' {
  declare module.exports: any;
}

declare module 'documentation/src/output/markdown' {
  declare module.exports: any;
}

declare module 'documentation/src/output/util/format_type' {
  declare module.exports: any;
}

declare module 'documentation/src/output/util/formatters' {
  declare module.exports: any;
}

declare module 'documentation/src/output/util/linker_stack' {
  declare module.exports: any;
}

declare module 'documentation/src/output/util/reroute_links' {
  declare module.exports: any;
}

declare module 'documentation/src/parse_markdown' {
  declare module.exports: any;
}

declare module 'documentation/src/parse' {
  declare module.exports: any;
}

declare module 'documentation/src/parsers/javascript' {
  declare module.exports: any;
}

declare module 'documentation/src/parsers/parse_to_ast' {
  declare module.exports: any;
}

declare module 'documentation/src/parsers/vue' {
  declare module.exports: any;
}

declare module 'documentation/src/serve/error_page' {
  declare module.exports: any;
}

declare module 'documentation/src/serve/server' {
  declare module.exports: any;
}

declare module 'documentation/src/smart_glob' {
  declare module.exports: any;
}

declare module 'documentation/src/sort' {
  declare module.exports: any;
}

declare module 'documentation/src/ts_doctrine' {
  declare module.exports: any;
}

declare module 'documentation/src/type_annotation' {
  declare module.exports: any;
}

declare module 'documentation/src/walk' {
  declare module.exports: any;
}

// Filename aliases
declare module 'documentation/babel.config.js' {
  declare module.exports: $Exports<'documentation/babel.config'>;
}
declare module 'documentation/bin/documentation.js' {
  declare module.exports: $Exports<'documentation/bin/documentation'>;
}
declare module 'documentation/declarations/comment.js' {
  declare module.exports: $Exports<'documentation/declarations/comment'>;
}
declare module 'documentation/src/commands/build.js' {
  declare module.exports: $Exports<'documentation/src/commands/build'>;
}
declare module 'documentation/src/commands/index' {
  declare module.exports: $Exports<'documentation/src/commands'>;
}
declare module 'documentation/src/commands/index.js' {
  declare module.exports: $Exports<'documentation/src/commands'>;
}
declare module 'documentation/src/commands/lint.js' {
  declare module.exports: $Exports<'documentation/src/commands/lint'>;
}
declare module 'documentation/src/commands/readme.js' {
  declare module.exports: $Exports<'documentation/src/commands/readme'>;
}
declare module 'documentation/src/commands/serve.js' {
  declare module.exports: $Exports<'documentation/src/commands/serve'>;
}
declare module 'documentation/src/commands/shared_options.js' {
  declare module.exports: $Exports<'documentation/src/commands/shared_options'>;
}
declare module 'documentation/src/default_theme/assets/anchor.js' {
  declare module.exports: $Exports<'documentation/src/default_theme/assets/anchor'>;
}
declare module 'documentation/src/default_theme/assets/site.js' {
  declare module.exports: $Exports<'documentation/src/default_theme/assets/site'>;
}
declare module 'documentation/src/default_theme/assets/split.js' {
  declare module.exports: $Exports<'documentation/src/default_theme/assets/split'>;
}
declare module 'documentation/src/default_theme/index' {
  declare module.exports: $Exports<'documentation/src/default_theme'>;
}
declare module 'documentation/src/default_theme/index.js' {
  declare module.exports: $Exports<'documentation/src/default_theme'>;
}
declare module 'documentation/src/extractors/comments.js' {
  declare module.exports: $Exports<'documentation/src/extractors/comments'>;
}
declare module 'documentation/src/extractors/exported.js' {
  declare module.exports: $Exports<'documentation/src/extractors/exported'>;
}
declare module 'documentation/src/filter_access.js' {
  declare module.exports: $Exports<'documentation/src/filter_access'>;
}
declare module 'documentation/src/flow_doctrine.js' {
  declare module.exports: $Exports<'documentation/src/flow_doctrine'>;
}
declare module 'documentation/src/garbage_collect.js' {
  declare module.exports: $Exports<'documentation/src/garbage_collect'>;
}
declare module 'documentation/src/get-readme-file.js' {
  declare module.exports: $Exports<'documentation/src/get-readme-file'>;
}
declare module 'documentation/src/git/find_git.js' {
  declare module.exports: $Exports<'documentation/src/git/find_git'>;
}
declare module 'documentation/src/git/url_prefix.js' {
  declare module.exports: $Exports<'documentation/src/git/url_prefix'>;
}
declare module 'documentation/src/github.js' {
  declare module.exports: $Exports<'documentation/src/github'>;
}
declare module 'documentation/src/hierarchy.js' {
  declare module.exports: $Exports<'documentation/src/hierarchy'>;
}
declare module 'documentation/src/index' {
  declare module.exports: $Exports<'documentation/src'>;
}
declare module 'documentation/src/index.js' {
  declare module.exports: $Exports<'documentation/src'>;
}
declare module 'documentation/src/infer/access.js' {
  declare module.exports: $Exports<'documentation/src/infer/access'>;
}
declare module 'documentation/src/infer/augments.js' {
  declare module.exports: $Exports<'documentation/src/infer/augments'>;
}
declare module 'documentation/src/infer/finders.js' {
  declare module.exports: $Exports<'documentation/src/infer/finders'>;
}
declare module 'documentation/src/infer/implements.js' {
  declare module.exports: $Exports<'documentation/src/infer/implements'>;
}
declare module 'documentation/src/infer/kind.js' {
  declare module.exports: $Exports<'documentation/src/infer/kind'>;
}
declare module 'documentation/src/infer/membership.js' {
  declare module.exports: $Exports<'documentation/src/infer/membership'>;
}
declare module 'documentation/src/infer/name.js' {
  declare module.exports: $Exports<'documentation/src/infer/name'>;
}
declare module 'documentation/src/infer/params.js' {
  declare module.exports: $Exports<'documentation/src/infer/params'>;
}
declare module 'documentation/src/infer/properties.js' {
  declare module.exports: $Exports<'documentation/src/infer/properties'>;
}
declare module 'documentation/src/infer/return.js' {
  declare module.exports: $Exports<'documentation/src/infer/return'>;
}
declare module 'documentation/src/infer/type.js' {
  declare module.exports: $Exports<'documentation/src/infer/type'>;
}
declare module 'documentation/src/inline_tokenizer.js' {
  declare module.exports: $Exports<'documentation/src/inline_tokenizer'>;
}
declare module 'documentation/src/input/dependency.js' {
  declare module.exports: $Exports<'documentation/src/input/dependency'>;
}
declare module 'documentation/src/input/shallow.js' {
  declare module.exports: $Exports<'documentation/src/input/shallow'>;
}
declare module 'documentation/src/is_jsdoc_comment.js' {
  declare module.exports: $Exports<'documentation/src/is_jsdoc_comment'>;
}
declare module 'documentation/src/lint.js' {
  declare module.exports: $Exports<'documentation/src/lint'>;
}
declare module 'documentation/src/merge_config.js' {
  declare module.exports: $Exports<'documentation/src/merge_config'>;
}
declare module 'documentation/src/module_filters.js' {
  declare module.exports: $Exports<'documentation/src/module_filters'>;
}
declare module 'documentation/src/nest.js' {
  declare module.exports: $Exports<'documentation/src/nest'>;
}
declare module 'documentation/src/output/highlighter.js' {
  declare module.exports: $Exports<'documentation/src/output/highlighter'>;
}
declare module 'documentation/src/output/html.js' {
  declare module.exports: $Exports<'documentation/src/output/html'>;
}
declare module 'documentation/src/output/json.js' {
  declare module.exports: $Exports<'documentation/src/output/json'>;
}
declare module 'documentation/src/output/markdown_ast.js' {
  declare module.exports: $Exports<'documentation/src/output/markdown_ast'>;
}
declare module 'documentation/src/output/markdown.js' {
  declare module.exports: $Exports<'documentation/src/output/markdown'>;
}
declare module 'documentation/src/output/util/format_type.js' {
  declare module.exports: $Exports<'documentation/src/output/util/format_type'>;
}
declare module 'documentation/src/output/util/formatters.js' {
  declare module.exports: $Exports<'documentation/src/output/util/formatters'>;
}
declare module 'documentation/src/output/util/linker_stack.js' {
  declare module.exports: $Exports<'documentation/src/output/util/linker_stack'>;
}
declare module 'documentation/src/output/util/reroute_links.js' {
  declare module.exports: $Exports<'documentation/src/output/util/reroute_links'>;
}
declare module 'documentation/src/parse_markdown.js' {
  declare module.exports: $Exports<'documentation/src/parse_markdown'>;
}
declare module 'documentation/src/parse.js' {
  declare module.exports: $Exports<'documentation/src/parse'>;
}
declare module 'documentation/src/parsers/javascript.js' {
  declare module.exports: $Exports<'documentation/src/parsers/javascript'>;
}
declare module 'documentation/src/parsers/parse_to_ast.js' {
  declare module.exports: $Exports<'documentation/src/parsers/parse_to_ast'>;
}
declare module 'documentation/src/parsers/vue.js' {
  declare module.exports: $Exports<'documentation/src/parsers/vue'>;
}
declare module 'documentation/src/serve/error_page.js' {
  declare module.exports: $Exports<'documentation/src/serve/error_page'>;
}
declare module 'documentation/src/serve/server.js' {
  declare module.exports: $Exports<'documentation/src/serve/server'>;
}
declare module 'documentation/src/smart_glob.js' {
  declare module.exports: $Exports<'documentation/src/smart_glob'>;
}
declare module 'documentation/src/sort.js' {
  declare module.exports: $Exports<'documentation/src/sort'>;
}
declare module 'documentation/src/ts_doctrine.js' {
  declare module.exports: $Exports<'documentation/src/ts_doctrine'>;
}
declare module 'documentation/src/type_annotation.js' {
  declare module.exports: $Exports<'documentation/src/type_annotation'>;
}
declare module 'documentation/src/walk.js' {
  declare module.exports: $Exports<'documentation/src/walk'>;
}
