// flow-typed signature: ccd5c457558d39d0bd3625a83db5f4fb
// flow-typed version: <<STUB>>/eslint-config-airbnb-base_v^13.1.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-airbnb-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-airbnb-base' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-airbnb-base/legacy' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb-base/rules/best-practices' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb-base/rules/errors' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb-base/rules/es6' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb-base/rules/imports' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb-base/rules/node' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb-base/rules/strict' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb-base/rules/style' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb-base/rules/variables' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb-base/test/requires' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb-base/test/test-base' {
  declare module.exports: any;
}

declare module 'eslint-config-airbnb-base/whitespace' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-airbnb-base/index' {
  declare module.exports: $Exports<'eslint-config-airbnb-base'>;
}
declare module 'eslint-config-airbnb-base/index.js' {
  declare module.exports: $Exports<'eslint-config-airbnb-base'>;
}
declare module 'eslint-config-airbnb-base/legacy.js' {
  declare module.exports: $Exports<'eslint-config-airbnb-base/legacy'>;
}
declare module 'eslint-config-airbnb-base/rules/best-practices.js' {
  declare module.exports: $Exports<'eslint-config-airbnb-base/rules/best-practices'>;
}
declare module 'eslint-config-airbnb-base/rules/errors.js' {
  declare module.exports: $Exports<'eslint-config-airbnb-base/rules/errors'>;
}
declare module 'eslint-config-airbnb-base/rules/es6.js' {
  declare module.exports: $Exports<'eslint-config-airbnb-base/rules/es6'>;
}
declare module 'eslint-config-airbnb-base/rules/imports.js' {
  declare module.exports: $Exports<'eslint-config-airbnb-base/rules/imports'>;
}
declare module 'eslint-config-airbnb-base/rules/node.js' {
  declare module.exports: $Exports<'eslint-config-airbnb-base/rules/node'>;
}
declare module 'eslint-config-airbnb-base/rules/strict.js' {
  declare module.exports: $Exports<'eslint-config-airbnb-base/rules/strict'>;
}
declare module 'eslint-config-airbnb-base/rules/style.js' {
  declare module.exports: $Exports<'eslint-config-airbnb-base/rules/style'>;
}
declare module 'eslint-config-airbnb-base/rules/variables.js' {
  declare module.exports: $Exports<'eslint-config-airbnb-base/rules/variables'>;
}
declare module 'eslint-config-airbnb-base/test/requires.js' {
  declare module.exports: $Exports<'eslint-config-airbnb-base/test/requires'>;
}
declare module 'eslint-config-airbnb-base/test/test-base.js' {
  declare module.exports: $Exports<'eslint-config-airbnb-base/test/test-base'>;
}
declare module 'eslint-config-airbnb-base/whitespace.js' {
  declare module.exports: $Exports<'eslint-config-airbnb-base/whitespace'>;
}
