// flow-typed signature: 620f45aca8c17cdf2ff8e25c91535374
// flow-typed version: <<STUB>>/ghooks_v^1.3.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ghooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ghooks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ghooks/dist/hook.template' {
  declare module.exports: any;
}

declare module 'ghooks/dist/install' {
  declare module.exports: any;
}

declare module 'ghooks/dist/runner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ghooks/dist/hook.template.js' {
  declare module.exports: $Exports<'ghooks/dist/hook.template'>;
}
declare module 'ghooks/dist/install.js' {
  declare module.exports: $Exports<'ghooks/dist/install'>;
}
declare module 'ghooks/dist/runner.js' {
  declare module.exports: $Exports<'ghooks/dist/runner'>;
}
