// flow-typed signature: 8601f8419eaff4f764252fa509e9807d
// flow-typed version: <<STUB>>/jest-environment-jsdom_v^29.7.0/flow_v0.227.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-environment-jsdom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-environment-jsdom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-environment-jsdom/build' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-environment-jsdom/build/index' {
  declare module.exports: $Exports<'jest-environment-jsdom/build'>;
}
declare module 'jest-environment-jsdom/build/index.js' {
  declare module.exports: $Exports<'jest-environment-jsdom/build'>;
}
