// flow-typed signature: 904b56d5e5451ed3b052c83d38d35d71
// flow-typed version: <<STUB>>/lint-staged_v^15.2.1/flow_v0.227.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lint-staged'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lint-staged' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lint-staged/bin/lint-staged' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/chunkFiles' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/configFiles' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/dynamicImport' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/execGit' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/figures' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/file' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/generateTasks' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/getDiffCommand' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/getRenderer' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/getStagedFiles' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/gitWorkflow' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/groupFilesByConfig' {
  declare module.exports: any;
}

declare module 'lint-staged/lib' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/loadConfig' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/makeCmdTasks' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/messages' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/normalizePath' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/parseGitZOutput' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/printTaskOutput' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/readStdin' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/resolveConfig' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/resolveGitRepo' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/resolveTaskFn' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/runAll' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/searchConfigs' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/state' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/symbols' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/validateBraces' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/validateConfig' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/validateOptions' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lint-staged/bin/lint-staged.js' {
  declare module.exports: $Exports<'lint-staged/bin/lint-staged'>;
}
declare module 'lint-staged/lib/chunkFiles.js' {
  declare module.exports: $Exports<'lint-staged/lib/chunkFiles'>;
}
declare module 'lint-staged/lib/configFiles.js' {
  declare module.exports: $Exports<'lint-staged/lib/configFiles'>;
}
declare module 'lint-staged/lib/dynamicImport.js' {
  declare module.exports: $Exports<'lint-staged/lib/dynamicImport'>;
}
declare module 'lint-staged/lib/execGit.js' {
  declare module.exports: $Exports<'lint-staged/lib/execGit'>;
}
declare module 'lint-staged/lib/figures.js' {
  declare module.exports: $Exports<'lint-staged/lib/figures'>;
}
declare module 'lint-staged/lib/file.js' {
  declare module.exports: $Exports<'lint-staged/lib/file'>;
}
declare module 'lint-staged/lib/generateTasks.js' {
  declare module.exports: $Exports<'lint-staged/lib/generateTasks'>;
}
declare module 'lint-staged/lib/getDiffCommand.js' {
  declare module.exports: $Exports<'lint-staged/lib/getDiffCommand'>;
}
declare module 'lint-staged/lib/getRenderer.js' {
  declare module.exports: $Exports<'lint-staged/lib/getRenderer'>;
}
declare module 'lint-staged/lib/getStagedFiles.js' {
  declare module.exports: $Exports<'lint-staged/lib/getStagedFiles'>;
}
declare module 'lint-staged/lib/gitWorkflow.js' {
  declare module.exports: $Exports<'lint-staged/lib/gitWorkflow'>;
}
declare module 'lint-staged/lib/groupFilesByConfig.js' {
  declare module.exports: $Exports<'lint-staged/lib/groupFilesByConfig'>;
}
declare module 'lint-staged/lib/index' {
  declare module.exports: $Exports<'lint-staged/lib'>;
}
declare module 'lint-staged/lib/index.js' {
  declare module.exports: $Exports<'lint-staged/lib'>;
}
declare module 'lint-staged/lib/loadConfig.js' {
  declare module.exports: $Exports<'lint-staged/lib/loadConfig'>;
}
declare module 'lint-staged/lib/makeCmdTasks.js' {
  declare module.exports: $Exports<'lint-staged/lib/makeCmdTasks'>;
}
declare module 'lint-staged/lib/messages.js' {
  declare module.exports: $Exports<'lint-staged/lib/messages'>;
}
declare module 'lint-staged/lib/normalizePath.js' {
  declare module.exports: $Exports<'lint-staged/lib/normalizePath'>;
}
declare module 'lint-staged/lib/parseGitZOutput.js' {
  declare module.exports: $Exports<'lint-staged/lib/parseGitZOutput'>;
}
declare module 'lint-staged/lib/printTaskOutput.js' {
  declare module.exports: $Exports<'lint-staged/lib/printTaskOutput'>;
}
declare module 'lint-staged/lib/readStdin.js' {
  declare module.exports: $Exports<'lint-staged/lib/readStdin'>;
}
declare module 'lint-staged/lib/resolveConfig.js' {
  declare module.exports: $Exports<'lint-staged/lib/resolveConfig'>;
}
declare module 'lint-staged/lib/resolveGitRepo.js' {
  declare module.exports: $Exports<'lint-staged/lib/resolveGitRepo'>;
}
declare module 'lint-staged/lib/resolveTaskFn.js' {
  declare module.exports: $Exports<'lint-staged/lib/resolveTaskFn'>;
}
declare module 'lint-staged/lib/runAll.js' {
  declare module.exports: $Exports<'lint-staged/lib/runAll'>;
}
declare module 'lint-staged/lib/searchConfigs.js' {
  declare module.exports: $Exports<'lint-staged/lib/searchConfigs'>;
}
declare module 'lint-staged/lib/state.js' {
  declare module.exports: $Exports<'lint-staged/lib/state'>;
}
declare module 'lint-staged/lib/symbols.js' {
  declare module.exports: $Exports<'lint-staged/lib/symbols'>;
}
declare module 'lint-staged/lib/validateBraces.js' {
  declare module.exports: $Exports<'lint-staged/lib/validateBraces'>;
}
declare module 'lint-staged/lib/validateConfig.js' {
  declare module.exports: $Exports<'lint-staged/lib/validateConfig'>;
}
declare module 'lint-staged/lib/validateOptions.js' {
  declare module.exports: $Exports<'lint-staged/lib/validateOptions'>;
}
