// flow-typed signature: 477c6b780c252350c538c6034bfeec7a
// flow-typed version: <<STUB>>/polished_v1.1.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'polished'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'polished' {
  declare module.exports: any;
}
