// flow-typed signature: b49126d6c3f0a6ce9bf7341af592c69a
// flow-typed version: <<STUB>>/pushstate-server_v^3.1.0/flow_v0.227.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pushstate-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pushstate-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pushstate-server/test/fixtures/cat' {
  declare module.exports: any;
}

declare module 'pushstate-server/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pushstate-server/index' {
  declare module.exports: $Exports<'pushstate-server'>;
}
declare module 'pushstate-server/index.js' {
  declare module.exports: $Exports<'pushstate-server'>;
}
declare module 'pushstate-server/test/fixtures/cat.js' {
  declare module.exports: $Exports<'pushstate-server/test/fixtures/cat'>;
}
declare module 'pushstate-server/test/index' {
  declare module.exports: $Exports<'pushstate-server/test'>;
}
declare module 'pushstate-server/test/index.js' {
  declare module.exports: $Exports<'pushstate-server/test'>;
}
