// flow-typed signature: d2564d490974b5b1c7760035528c98d0
// flow-typed version: <<STUB>>/rollup-plugin-terser_v^7.0.2/flow_v0.227.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-terser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-terser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-terser/rollup-plugin-terser' {
  declare module.exports: any;
}

declare module 'rollup-plugin-terser/transform' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-terser/rollup-plugin-terser.js' {
  declare module.exports: $Exports<'rollup-plugin-terser/rollup-plugin-terser'>;
}
declare module 'rollup-plugin-terser/transform.js' {
  declare module.exports: $Exports<'rollup-plugin-terser/transform'>;
}
