// flow-typed signature: 4699c84aa2c1b0ee510c13747c0806b2
// flow-typed version: <<STUB>>/rollup_v^4.9.6/flow_v0.227.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup/dist/es/getLogFilter' {
  declare module.exports: any;
}

declare module 'rollup/dist/es/parseAst' {
  declare module.exports: any;
}

declare module 'rollup/dist/es/rollup' {
  declare module.exports: any;
}

declare module 'rollup/dist/es/shared/node-entry' {
  declare module.exports: any;
}

declare module 'rollup/dist/es/shared/parseAst' {
  declare module.exports: any;
}

declare module 'rollup/dist/es/shared/watch' {
  declare module.exports: any;
}

declare module 'rollup/dist/getLogFilter' {
  declare module.exports: any;
}

declare module 'rollup/dist/loadConfigFile' {
  declare module.exports: any;
}

declare module 'rollup/dist/native' {
  declare module.exports: any;
}

declare module 'rollup/dist/parseAst' {
  declare module.exports: any;
}

declare module 'rollup/dist/rollup' {
  declare module.exports: any;
}

declare module 'rollup/dist/shared/fsevents-importer' {
  declare module.exports: any;
}

declare module 'rollup/dist/shared' {
  declare module.exports: any;
}

declare module 'rollup/dist/shared/loadConfigFile' {
  declare module.exports: any;
}

declare module 'rollup/dist/shared/parseAst' {
  declare module.exports: any;
}

declare module 'rollup/dist/shared/rollup' {
  declare module.exports: any;
}

declare module 'rollup/dist/shared/watch-cli' {
  declare module.exports: any;
}

declare module 'rollup/dist/shared/watch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup/dist/es/getLogFilter.js' {
  declare module.exports: $Exports<'rollup/dist/es/getLogFilter'>;
}
declare module 'rollup/dist/es/parseAst.js' {
  declare module.exports: $Exports<'rollup/dist/es/parseAst'>;
}
declare module 'rollup/dist/es/rollup.js' {
  declare module.exports: $Exports<'rollup/dist/es/rollup'>;
}
declare module 'rollup/dist/es/shared/node-entry.js' {
  declare module.exports: $Exports<'rollup/dist/es/shared/node-entry'>;
}
declare module 'rollup/dist/es/shared/parseAst.js' {
  declare module.exports: $Exports<'rollup/dist/es/shared/parseAst'>;
}
declare module 'rollup/dist/es/shared/watch.js' {
  declare module.exports: $Exports<'rollup/dist/es/shared/watch'>;
}
declare module 'rollup/dist/getLogFilter.js' {
  declare module.exports: $Exports<'rollup/dist/getLogFilter'>;
}
declare module 'rollup/dist/loadConfigFile.js' {
  declare module.exports: $Exports<'rollup/dist/loadConfigFile'>;
}
declare module 'rollup/dist/native.js' {
  declare module.exports: $Exports<'rollup/dist/native'>;
}
declare module 'rollup/dist/parseAst.js' {
  declare module.exports: $Exports<'rollup/dist/parseAst'>;
}
declare module 'rollup/dist/rollup.js' {
  declare module.exports: $Exports<'rollup/dist/rollup'>;
}
declare module 'rollup/dist/shared/fsevents-importer.js' {
  declare module.exports: $Exports<'rollup/dist/shared/fsevents-importer'>;
}
declare module 'rollup/dist/shared/index' {
  declare module.exports: $Exports<'rollup/dist/shared'>;
}
declare module 'rollup/dist/shared/index.js' {
  declare module.exports: $Exports<'rollup/dist/shared'>;
}
declare module 'rollup/dist/shared/loadConfigFile.js' {
  declare module.exports: $Exports<'rollup/dist/shared/loadConfigFile'>;
}
declare module 'rollup/dist/shared/parseAst.js' {
  declare module.exports: $Exports<'rollup/dist/shared/parseAst'>;
}
declare module 'rollup/dist/shared/rollup.js' {
  declare module.exports: $Exports<'rollup/dist/shared/rollup'>;
}
declare module 'rollup/dist/shared/watch-cli.js' {
  declare module.exports: $Exports<'rollup/dist/shared/watch-cli'>;
}
declare module 'rollup/dist/shared/watch.js' {
  declare module.exports: $Exports<'rollup/dist/shared/watch'>;
}
