// flow-typed signature: b1a0c4515f99586d90968e6dff37d3ba
// flow-typed version: <<STUB>>/semantic-release_v^15.13.16/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'semantic-release'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'semantic-release' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'semantic-release/bin/semantic-release' {
  declare module.exports: any;
}

declare module 'semantic-release/cli' {
  declare module.exports: any;
}

declare module 'semantic-release/lib/definitions/constants' {
  declare module.exports: any;
}

declare module 'semantic-release/lib/definitions/errors' {
  declare module.exports: any;
}

declare module 'semantic-release/lib/definitions/plugins' {
  declare module.exports: any;
}

declare module 'semantic-release/lib/get-commits' {
  declare module.exports: any;
}

declare module 'semantic-release/lib/get-config' {
  declare module.exports: any;
}

declare module 'semantic-release/lib/get-error' {
  declare module.exports: any;
}

declare module 'semantic-release/lib/get-git-auth-url' {
  declare module.exports: any;
}

declare module 'semantic-release/lib/get-last-release' {
  declare module.exports: any;
}

declare module 'semantic-release/lib/get-logger' {
  declare module.exports: any;
}

declare module 'semantic-release/lib/get-next-version' {
  declare module.exports: any;
}

declare module 'semantic-release/lib/git' {
  declare module.exports: any;
}

declare module 'semantic-release/lib/hide-sensitive' {
  declare module.exports: any;
}

declare module 'semantic-release/lib/plugins/index' {
  declare module.exports: any;
}

declare module 'semantic-release/lib/plugins/normalize' {
  declare module.exports: any;
}

declare module 'semantic-release/lib/plugins/pipeline' {
  declare module.exports: any;
}

declare module 'semantic-release/lib/plugins/utils' {
  declare module.exports: any;
}

declare module 'semantic-release/lib/utils' {
  declare module.exports: any;
}

declare module 'semantic-release/lib/verify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'semantic-release/bin/semantic-release.js' {
  declare module.exports: $Exports<'semantic-release/bin/semantic-release'>;
}
declare module 'semantic-release/cli.js' {
  declare module.exports: $Exports<'semantic-release/cli'>;
}
declare module 'semantic-release/index' {
  declare module.exports: $Exports<'semantic-release'>;
}
declare module 'semantic-release/index.js' {
  declare module.exports: $Exports<'semantic-release'>;
}
declare module 'semantic-release/lib/definitions/constants.js' {
  declare module.exports: $Exports<'semantic-release/lib/definitions/constants'>;
}
declare module 'semantic-release/lib/definitions/errors.js' {
  declare module.exports: $Exports<'semantic-release/lib/definitions/errors'>;
}
declare module 'semantic-release/lib/definitions/plugins.js' {
  declare module.exports: $Exports<'semantic-release/lib/definitions/plugins'>;
}
declare module 'semantic-release/lib/get-commits.js' {
  declare module.exports: $Exports<'semantic-release/lib/get-commits'>;
}
declare module 'semantic-release/lib/get-config.js' {
  declare module.exports: $Exports<'semantic-release/lib/get-config'>;
}
declare module 'semantic-release/lib/get-error.js' {
  declare module.exports: $Exports<'semantic-release/lib/get-error'>;
}
declare module 'semantic-release/lib/get-git-auth-url.js' {
  declare module.exports: $Exports<'semantic-release/lib/get-git-auth-url'>;
}
declare module 'semantic-release/lib/get-last-release.js' {
  declare module.exports: $Exports<'semantic-release/lib/get-last-release'>;
}
declare module 'semantic-release/lib/get-logger.js' {
  declare module.exports: $Exports<'semantic-release/lib/get-logger'>;
}
declare module 'semantic-release/lib/get-next-version.js' {
  declare module.exports: $Exports<'semantic-release/lib/get-next-version'>;
}
declare module 'semantic-release/lib/git.js' {
  declare module.exports: $Exports<'semantic-release/lib/git'>;
}
declare module 'semantic-release/lib/hide-sensitive.js' {
  declare module.exports: $Exports<'semantic-release/lib/hide-sensitive'>;
}
declare module 'semantic-release/lib/plugins/index.js' {
  declare module.exports: $Exports<'semantic-release/lib/plugins/index'>;
}
declare module 'semantic-release/lib/plugins/normalize.js' {
  declare module.exports: $Exports<'semantic-release/lib/plugins/normalize'>;
}
declare module 'semantic-release/lib/plugins/pipeline.js' {
  declare module.exports: $Exports<'semantic-release/lib/plugins/pipeline'>;
}
declare module 'semantic-release/lib/plugins/utils.js' {
  declare module.exports: $Exports<'semantic-release/lib/plugins/utils'>;
}
declare module 'semantic-release/lib/utils.js' {
  declare module.exports: $Exports<'semantic-release/lib/utils'>;
}
declare module 'semantic-release/lib/verify.js' {
  declare module.exports: $Exports<'semantic-release/lib/verify'>;
}
