// flow-typed signature: 7ba2de262527fa595452e805776e4957
// flow-typed version: <<STUB>>/semantic-release_v^4.3.5/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'semantic-release'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'semantic-release' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'semantic-release/bin/semantic-release' {
  declare module.exports: any;
}

declare module 'semantic-release/dist/index' {
  declare module.exports: any;
}

declare module 'semantic-release/dist/lib/commits' {
  declare module.exports: any;
}

declare module 'semantic-release/dist/lib/get-registry' {
  declare module.exports: any;
}

declare module 'semantic-release/dist/lib/plugin-noop' {
  declare module.exports: any;
}

declare module 'semantic-release/dist/lib/plugins' {
  declare module.exports: any;
}

declare module 'semantic-release/dist/lib/type' {
  declare module.exports: any;
}

declare module 'semantic-release/dist/lib/verify' {
  declare module.exports: any;
}

declare module 'semantic-release/dist/post' {
  declare module.exports: any;
}

declare module 'semantic-release/dist/pre' {
  declare module.exports: any;
}

declare module 'semantic-release/test/lib/base-scenario' {
  declare module.exports: any;
}

declare module 'semantic-release/test/lib/test-module' {
  declare module.exports: any;
}

declare module 'semantic-release/test/mocks/child-process' {
  declare module.exports: any;
}

declare module 'semantic-release/test/mocks/git-head' {
  declare module.exports: any;
}

declare module 'semantic-release/test/mocks/github' {
  declare module.exports: any;
}

declare module 'semantic-release/test/mocks/plugin-error-a' {
  declare module.exports: any;
}

declare module 'semantic-release/test/mocks/plugin-error-b' {
  declare module.exports: any;
}

declare module 'semantic-release/test/mocks/plugin-result-a' {
  declare module.exports: any;
}

declare module 'semantic-release/test/mocks/plugin-result-b' {
  declare module.exports: any;
}

declare module 'semantic-release/test/mocks/registry' {
  declare module.exports: any;
}

declare module 'semantic-release/test/registry/index' {
  declare module.exports: any;
}

declare module 'semantic-release/test/scenarios/pre' {
  declare module.exports: any;
}

declare module 'semantic-release/test/specs/commits' {
  declare module.exports: any;
}

declare module 'semantic-release/test/specs/get-registry' {
  declare module.exports: any;
}

declare module 'semantic-release/test/specs/plugins' {
  declare module.exports: any;
}

declare module 'semantic-release/test/specs/post' {
  declare module.exports: any;
}

declare module 'semantic-release/test/specs/pre' {
  declare module.exports: any;
}

declare module 'semantic-release/test/specs/type' {
  declare module.exports: any;
}

declare module 'semantic-release/test/specs/verify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'semantic-release/bin/semantic-release.js' {
  declare module.exports: $Exports<'semantic-release/bin/semantic-release'>;
}
declare module 'semantic-release/dist/index.js' {
  declare module.exports: $Exports<'semantic-release/dist/index'>;
}
declare module 'semantic-release/dist/lib/commits.js' {
  declare module.exports: $Exports<'semantic-release/dist/lib/commits'>;
}
declare module 'semantic-release/dist/lib/get-registry.js' {
  declare module.exports: $Exports<'semantic-release/dist/lib/get-registry'>;
}
declare module 'semantic-release/dist/lib/plugin-noop.js' {
  declare module.exports: $Exports<'semantic-release/dist/lib/plugin-noop'>;
}
declare module 'semantic-release/dist/lib/plugins.js' {
  declare module.exports: $Exports<'semantic-release/dist/lib/plugins'>;
}
declare module 'semantic-release/dist/lib/type.js' {
  declare module.exports: $Exports<'semantic-release/dist/lib/type'>;
}
declare module 'semantic-release/dist/lib/verify.js' {
  declare module.exports: $Exports<'semantic-release/dist/lib/verify'>;
}
declare module 'semantic-release/dist/post.js' {
  declare module.exports: $Exports<'semantic-release/dist/post'>;
}
declare module 'semantic-release/dist/pre.js' {
  declare module.exports: $Exports<'semantic-release/dist/pre'>;
}
declare module 'semantic-release/test/lib/base-scenario.js' {
  declare module.exports: $Exports<'semantic-release/test/lib/base-scenario'>;
}
declare module 'semantic-release/test/lib/test-module.js' {
  declare module.exports: $Exports<'semantic-release/test/lib/test-module'>;
}
declare module 'semantic-release/test/mocks/child-process.js' {
  declare module.exports: $Exports<'semantic-release/test/mocks/child-process'>;
}
declare module 'semantic-release/test/mocks/git-head.js' {
  declare module.exports: $Exports<'semantic-release/test/mocks/git-head'>;
}
declare module 'semantic-release/test/mocks/github.js' {
  declare module.exports: $Exports<'semantic-release/test/mocks/github'>;
}
declare module 'semantic-release/test/mocks/plugin-error-a.js' {
  declare module.exports: $Exports<'semantic-release/test/mocks/plugin-error-a'>;
}
declare module 'semantic-release/test/mocks/plugin-error-b.js' {
  declare module.exports: $Exports<'semantic-release/test/mocks/plugin-error-b'>;
}
declare module 'semantic-release/test/mocks/plugin-result-a.js' {
  declare module.exports: $Exports<'semantic-release/test/mocks/plugin-result-a'>;
}
declare module 'semantic-release/test/mocks/plugin-result-b.js' {
  declare module.exports: $Exports<'semantic-release/test/mocks/plugin-result-b'>;
}
declare module 'semantic-release/test/mocks/registry.js' {
  declare module.exports: $Exports<'semantic-release/test/mocks/registry'>;
}
declare module 'semantic-release/test/registry/index.js' {
  declare module.exports: $Exports<'semantic-release/test/registry/index'>;
}
declare module 'semantic-release/test/scenarios/pre.js' {
  declare module.exports: $Exports<'semantic-release/test/scenarios/pre'>;
}
declare module 'semantic-release/test/specs/commits.js' {
  declare module.exports: $Exports<'semantic-release/test/specs/commits'>;
}
declare module 'semantic-release/test/specs/get-registry.js' {
  declare module.exports: $Exports<'semantic-release/test/specs/get-registry'>;
}
declare module 'semantic-release/test/specs/plugins.js' {
  declare module.exports: $Exports<'semantic-release/test/specs/plugins'>;
}
declare module 'semantic-release/test/specs/post.js' {
  declare module.exports: $Exports<'semantic-release/test/specs/post'>;
}
declare module 'semantic-release/test/specs/pre.js' {
  declare module.exports: $Exports<'semantic-release/test/specs/pre'>;
}
declare module 'semantic-release/test/specs/type.js' {
  declare module.exports: $Exports<'semantic-release/test/specs/type'>;
}
declare module 'semantic-release/test/specs/verify.js' {
  declare module.exports: $Exports<'semantic-release/test/specs/verify'>;
}
