// flow-typed signature: 9a5de2de668270f8fbaab01d9db173bb
// flow-typed version: <<STUB>>/shx_v^0.2.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shx/lib/cli' {
  declare module.exports: any;
}

declare module 'shx/lib/config' {
  declare module.exports: any;
}

declare module 'shx/lib/help' {
  declare module.exports: any;
}

declare module 'shx/lib/printCmdRet' {
  declare module.exports: any;
}

declare module 'shx/lib/shx' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shx/lib/cli.js' {
  declare module.exports: $Exports<'shx/lib/cli'>;
}
declare module 'shx/lib/config.js' {
  declare module.exports: $Exports<'shx/lib/config'>;
}
declare module 'shx/lib/help.js' {
  declare module.exports: $Exports<'shx/lib/help'>;
}
declare module 'shx/lib/printCmdRet.js' {
  declare module.exports: $Exports<'shx/lib/printCmdRet'>;
}
declare module 'shx/lib/shx.js' {
  declare module.exports: $Exports<'shx/lib/shx'>;
}
