// flow-typed signature: 9d4637931a0dd8e5a21d467e00d8b468
// flow-typed version: <<STUB>>/validate-commit-msg_v^2.8.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'validate-commit-msg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'validate-commit-msg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'validate-commit-msg/lib/cli' {
  declare module.exports: any;
}

declare module 'validate-commit-msg/lib/config' {
  declare module.exports: any;
}

declare module 'validate-commit-msg/lib/getGitFolder' {
  declare module.exports: any;
}

declare module 'validate-commit-msg/lib/validateMessage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'validate-commit-msg/index' {
  declare module.exports: $Exports<'validate-commit-msg'>;
}
declare module 'validate-commit-msg/index.js' {
  declare module.exports: $Exports<'validate-commit-msg'>;
}
declare module 'validate-commit-msg/lib/cli.js' {
  declare module.exports: $Exports<'validate-commit-msg/lib/cli'>;
}
declare module 'validate-commit-msg/lib/config.js' {
  declare module.exports: $Exports<'validate-commit-msg/lib/config'>;
}
declare module 'validate-commit-msg/lib/getGitFolder.js' {
  declare module.exports: $Exports<'validate-commit-msg/lib/getGitFolder'>;
}
declare module 'validate-commit-msg/lib/validateMessage.js' {
  declare module.exports: $Exports<'validate-commit-msg/lib/validateMessage'>;
}
