// flow-typed signature: dc42220fd47e405ae05a29de5afd4f5a
// flow-typed version: <<STUB>>/vinyl-fs_v^3.0.2/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vinyl-fs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vinyl-fs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vinyl-fs/lib/constants' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/dest/index' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/dest/options' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/dest/prepare' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/dest/sourcemap' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/dest/write-contents/index' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/dest/write-contents/write-buffer' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/dest/write-contents/write-dir' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/dest/write-contents/write-stream' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/dest/write-contents/write-symbolic-link' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/file-operations' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/src/index' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/src/options' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/src/prepare' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/src/read-contents/index' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/src/read-contents/read-buffer' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/src/read-contents/read-dir' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/src/read-contents/read-stream' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/src/read-contents/read-symbolic-link' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/src/resolve-symlinks' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/src/sourcemap' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/src/wrap-vinyl' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/symlink/index' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/symlink/link-file' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/symlink/options' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/symlink/prepare' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vinyl-fs/index' {
  declare module.exports: $Exports<'vinyl-fs'>;
}
declare module 'vinyl-fs/index.js' {
  declare module.exports: $Exports<'vinyl-fs'>;
}
declare module 'vinyl-fs/lib/constants.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/constants'>;
}
declare module 'vinyl-fs/lib/dest/index.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/dest/index'>;
}
declare module 'vinyl-fs/lib/dest/options.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/dest/options'>;
}
declare module 'vinyl-fs/lib/dest/prepare.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/dest/prepare'>;
}
declare module 'vinyl-fs/lib/dest/sourcemap.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/dest/sourcemap'>;
}
declare module 'vinyl-fs/lib/dest/write-contents/index.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/dest/write-contents/index'>;
}
declare module 'vinyl-fs/lib/dest/write-contents/write-buffer.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/dest/write-contents/write-buffer'>;
}
declare module 'vinyl-fs/lib/dest/write-contents/write-dir.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/dest/write-contents/write-dir'>;
}
declare module 'vinyl-fs/lib/dest/write-contents/write-stream.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/dest/write-contents/write-stream'>;
}
declare module 'vinyl-fs/lib/dest/write-contents/write-symbolic-link.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/dest/write-contents/write-symbolic-link'>;
}
declare module 'vinyl-fs/lib/file-operations.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/file-operations'>;
}
declare module 'vinyl-fs/lib/src/index.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/src/index'>;
}
declare module 'vinyl-fs/lib/src/options.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/src/options'>;
}
declare module 'vinyl-fs/lib/src/prepare.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/src/prepare'>;
}
declare module 'vinyl-fs/lib/src/read-contents/index.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/src/read-contents/index'>;
}
declare module 'vinyl-fs/lib/src/read-contents/read-buffer.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/src/read-contents/read-buffer'>;
}
declare module 'vinyl-fs/lib/src/read-contents/read-dir.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/src/read-contents/read-dir'>;
}
declare module 'vinyl-fs/lib/src/read-contents/read-stream.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/src/read-contents/read-stream'>;
}
declare module 'vinyl-fs/lib/src/read-contents/read-symbolic-link.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/src/read-contents/read-symbolic-link'>;
}
declare module 'vinyl-fs/lib/src/resolve-symlinks.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/src/resolve-symlinks'>;
}
declare module 'vinyl-fs/lib/src/sourcemap.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/src/sourcemap'>;
}
declare module 'vinyl-fs/lib/src/wrap-vinyl.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/src/wrap-vinyl'>;
}
declare module 'vinyl-fs/lib/symlink/index.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/symlink/index'>;
}
declare module 'vinyl-fs/lib/symlink/link-file.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/symlink/link-file'>;
}
declare module 'vinyl-fs/lib/symlink/options.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/symlink/options'>;
}
declare module 'vinyl-fs/lib/symlink/prepare.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/symlink/prepare'>;
}
