// flow-typed signature: 0b40f7b5710f20d58f672abb2bb00bd0
// flow-typed version: <<STUB>>/vinyl_v^2.0.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vinyl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vinyl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vinyl/lib/inspect-stream' {
  declare module.exports: any;
}

declare module 'vinyl/lib/normalize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vinyl/index' {
  declare module.exports: $Exports<'vinyl'>;
}
declare module 'vinyl/index.js' {
  declare module.exports: $Exports<'vinyl'>;
}
declare module 'vinyl/lib/inspect-stream.js' {
  declare module.exports: $Exports<'vinyl/lib/inspect-stream'>;
}
declare module 'vinyl/lib/normalize.js' {
  declare module.exports: $Exports<'vinyl/lib/normalize'>;
}
