// flow-typed signature: 6a8f1a6a004f5d1688f3dac17e90ac90
// flow-typed version: <<STUB>>/vinyl-fs_v^2.4.4/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vinyl-fs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vinyl-fs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vinyl-fs/lib/dest/index' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/dest/writeContents/index' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/dest/writeContents/writeBuffer' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/dest/writeContents/writeDir' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/dest/writeContents/writeStream' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/dest/writeContents/writeSymbolicLink' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/fileOperations' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/filterSince' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/prepareWrite' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/sink' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/src/getContents/bufferFile' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/src/getContents/index' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/src/getContents/readDir' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/src/getContents/readSymbolicLink' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/src/getContents/streamFile' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/src/index' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/src/wrapWithVinylFile' {
  declare module.exports: any;
}

declare module 'vinyl-fs/lib/symlink/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vinyl-fs/index' {
  declare module.exports: $Exports<'vinyl-fs'>;
}
declare module 'vinyl-fs/index.js' {
  declare module.exports: $Exports<'vinyl-fs'>;
}
declare module 'vinyl-fs/lib/dest/index.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/dest/index'>;
}
declare module 'vinyl-fs/lib/dest/writeContents/index.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/dest/writeContents/index'>;
}
declare module 'vinyl-fs/lib/dest/writeContents/writeBuffer.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/dest/writeContents/writeBuffer'>;
}
declare module 'vinyl-fs/lib/dest/writeContents/writeDir.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/dest/writeContents/writeDir'>;
}
declare module 'vinyl-fs/lib/dest/writeContents/writeStream.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/dest/writeContents/writeStream'>;
}
declare module 'vinyl-fs/lib/dest/writeContents/writeSymbolicLink.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/dest/writeContents/writeSymbolicLink'>;
}
declare module 'vinyl-fs/lib/fileOperations.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/fileOperations'>;
}
declare module 'vinyl-fs/lib/filterSince.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/filterSince'>;
}
declare module 'vinyl-fs/lib/prepareWrite.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/prepareWrite'>;
}
declare module 'vinyl-fs/lib/sink.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/sink'>;
}
declare module 'vinyl-fs/lib/src/getContents/bufferFile.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/src/getContents/bufferFile'>;
}
declare module 'vinyl-fs/lib/src/getContents/index.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/src/getContents/index'>;
}
declare module 'vinyl-fs/lib/src/getContents/readDir.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/src/getContents/readDir'>;
}
declare module 'vinyl-fs/lib/src/getContents/readSymbolicLink.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/src/getContents/readSymbolicLink'>;
}
declare module 'vinyl-fs/lib/src/getContents/streamFile.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/src/getContents/streamFile'>;
}
declare module 'vinyl-fs/lib/src/index.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/src/index'>;
}
declare module 'vinyl-fs/lib/src/wrapWithVinylFile.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/src/wrapWithVinylFile'>;
}
declare module 'vinyl-fs/lib/symlink/index.js' {
  declare module.exports: $Exports<'vinyl-fs/lib/symlink/index'>;
}
