// @flow
/**
 * Handles the formatting of warnings and errors generated by modules.
 * @private
 */

function formatMessage(moduleInfo) {
  const header = `%c -- ${type} --------------------------------------------------- ${modulePath} -- `

  const messageBody = `%c


  ${messageBody}

  `

  const messageInfo = `%c
  Please see the documentation at %chttps://www.polished.js.org/${docPath} %cfor more information.

  `
  console.log(header + messageBody + messageInfo, 'padding: 2px; font-weight: bold; background: red; color: black', 'color: black', 'color: slategray', 'color: blue', 'color: slategray')
}

function generateMessage(type, moduleInfo, messageBody, docPath) {
  const message = formatMessage(type, moduleInfo, messageBody, docPath)
  console.log(message)
}

export default generateMessage
