// flow-typed signature: 4a75f65fe1b387bea4ad936551288188
// flow-typed version: <<STUB>>/@babel/eslint-parser_v^7.23.10/flow_v0.227.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any;
}
