// flow-typed signature: 2ef5b7b012d5c130f97d6223038ed9ef
// flow-typed version: <<STUB>>/@rollup/plugin-babel_v^6.0.4/flow_v0.227.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rollup/plugin-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rollup/plugin-babel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rollup/plugin-babel/dist/cjs' {
  declare module.exports: any;
}

declare module '@rollup/plugin-babel/dist/es' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rollup/plugin-babel/dist/cjs/index' {
  declare module.exports: $Exports<'@rollup/plugin-babel/dist/cjs'>;
}
declare module '@rollup/plugin-babel/dist/cjs/index.js' {
  declare module.exports: $Exports<'@rollup/plugin-babel/dist/cjs'>;
}
declare module '@rollup/plugin-babel/dist/es/index' {
  declare module.exports: $Exports<'@rollup/plugin-babel/dist/es'>;
}
declare module '@rollup/plugin-babel/dist/es/index.js' {
  declare module.exports: $Exports<'@rollup/plugin-babel/dist/es'>;
}
